### ISSUE TITLE
When i  execute the eval.py , the datahelper.py have type error issue.

### ISSUE THREAD

**Issue by kevin23916** [zake7749/Sequence-to-Sequence-101#3]
the error message is 
`    sequence += char
TypeError: must be str, not dict`

so I change the code to "sequence += str(char) "

but it still doesn't work.
<img width="783" alt="0318" src="https://user-images.githubusercontent.com/27729129/76936831-948e7e80-692e-11ea-84cb-fdd287d80339.png">

**Comment by zake7749** [comment]
Apologizes for the late response.
I just updated the repository to adapt PyTorch 1.4, which may help to solve this issue.
